---

# Requires "masternode" variable

- name: Get protx of registered masternodes
  ansible.builtin.set_fact:
    registered_masternode_protx: "{{ registered_masternode_protx + [{'masternode': item, 'protx': inner_item}] }}"
  loop: "{{ get_protx_list_result.stdout | from_json | json_query(\"[?state.ownerAddress=='\" + masternode.owner.address + \"'].proTxHash\") }}"
  loop_control:
    loop_var: inner_item
