---

drive_filebeat_inputs:
  - type: log
    enabled: "{{ drive_host_info.containers | length > 0 }}"
    json.message_key: message
    exclude_files: ['\.gz$']
    index: "logs-drive.abci-{{ hellar_network_name }}-%{[agent.version]}"
    paths:
      - "{{ abci_logs_path }}/drive-json*.log*"
    processors:
      - timestamp:
          field: json.timestamp
          layouts:
            - UNIX_MS
      - add_fields:
          target: event
          fields:
            dataset: "drive.abci-{{ hellar_network_name }}"
      - rename:
          fields:
            - from: "json.fields.message"
              to: "message"
            - from: "json.level"
              to: "log.level"
          ignore_missing: true
          fail_on_error: true
