---

platform_filebeat_inputs:
  - type: container
    enabled: "{{ tenderhellar_host_info.containers | length > 0 }}"
    json.message_key: message
    index: "logs-drive.tenderhellar-{{ hellar_network_name }}-%{[agent.version]}"
    paths:
      - '/var/lib/docker/containers/{{ tenderhellar_container_id }}/*.log'
    processors:
      - add_fields:
          target: event
          fields:
            dataset: "drive.tenderhellar-{{ hellar_network_name }}"
      - rename:
          fields:
            - from: "json.message"
              to: "message"
          ignore_missing: true
          fail_on_error: true
      - rename:
          fields:
            - from: "json.level"
              to: "log.level"
