---

- name: Configure ILM policy
  ansible.builtin.uri:
    url: http://localhost:9200/_ilm/policy/masternode-logs
    method: PUT
    status_code: 200
    user: '{{ elastic_username }}'
    password: '{{ elastic_password }}'
    body_format: json
    body: "{{ lookup('file', 'files/ilm_policy.json') }}"

- name: Set up core index template
  ansible.builtin.uri:
    url: http://localhost:9200/_index_template/logs-core
    method: PUT
    status_code: 200
    user: '{{ elastic_username }}'
    password: '{{ elastic_password }}'
    body_format: json
    body: "{{ lookup('file', 'files/index-templates/logs-core.json') }}"

- name: Set up abci index template
  ansible.builtin.uri:
    url: http://localhost:9200/_index_template/logs-drive.abci
    method: PUT
    status_code: 200
    user: '{{ elastic_username }}'
    password: '{{ elastic_password }}'
    body_format: json
    body: "{{ lookup('file', 'files/index-templates/logs-drive.abci.json') }}"

- name: Set up tenderhellar index template
  ansible.builtin.uri:
    url: http://localhost:9200/_index_template/logs-drive.tenderhellar
    method: PUT
    status_code: 200
    user: '{{ elastic_username }}'
    password: '{{ elastic_password }}'
    body_format: json
    body: "{{ lookup('file', 'files/index-templates/logs-drive.tenderhellar.json') }}"

- name: Set replica count to zero
  when: play_hosts | length == 1
  ansible.builtin.uri:
    url: http://localhost:9200/_settings
    method: PUT
    status_code: 200
    user: '{{ elastic_username }}'
    password: '{{ elastic_password }}'
    body_format: json
    body:
      index:
        number_of_replicas: 0

- name: Set up Kibana UI
  ansible.builtin.uri:
    url: http://localhost:5601/api/saved_objects/_bulk_create
    method: POST
    status_code: 200
    user: '{{ elastic_username }}'
    password: '{{ elastic_password }}'
    body_format: json
    force_basic_auth: true
    headers:
      kbn-xsrf: true
    body: "{{ lookup('file', 'files/infrastructure-ui-source.json') }}"
