---
- name: Set vars
  ansible.builtin.import_tasks: ./set_vars.yml

- name: Reindex hellarmate node
  ansible.builtin.command: "{{ hellarmate_cmd }} reindex -d --force"
  become: true
  become_user: hellarmate
  args:
    chdir: '{{ hellarmate_cwd }}'
  register: hellarmate_reindex
  changed_when: hellarmate_reindex.rc == 0
  when:
    - 'not filter_hostname or filter_hostname == inventory_hostname'
