---

- name: Disable pay-faucet
  ansible.builtin.systemd:
    name: 'pay-faucet'
    state: stopped
    enabled: false
  failed_when: false

- name: Disable hellard-generate-miner
  ansible.builtin.systemd:
    name: 'hellard-generate-miner'
    state: stopped
    enabled: false
  failed_when: false

- name: Collect list of docker services
  community.docker.docker_host_info:
    containers: true
  register: host_info

- name: Stop all docker containers
  community.docker.docker_container:
    name: '{{ item.Id }}'
    state: stopped
  with_items: '{{ host_info.containers }}'

- name: Remove all docker data
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: true
    networks: true
    volumes: true
    volumes_filters:
      all: true
    builder_cache: true

- name: Unmount data
  ansible.posix.mount:
    path: '{{ elastic_path }}/data'
    state: unmounted
  when: inventory_hostname in groups['logs_nodes']

- name: Delete hellarmate files
  ansible.builtin.import_role:
    name: hellarmate
    tasks_from: delete_files
  when: inventory_hostname in groups["hp_masternodes"]

- name: Delete hellar home dir
  ansible.builtin.file:
    state: absent
    path: "{{ hellard_home }}/"
