---

- name: Set up CloudWatch
  ansible.builtin.include_role:
    name: christiangda.amazon_cloudwatch_agent
  vars:
    cwa_agent_mode: "ec2"
    cwa_conf_json_file_content:
      agent:
        metrics_collection_interval: 300
        logfile: "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
        debug: false
      logs:
        logs_collected:
          files:
            collect_list:
              - file_path: "/var/log/message"
                log_group_name: "/var/log/message"
                log_stream_name: "{instance_id}"
      metrics:
        append_dimensions:
          AutoScalingGroupName: "${aws:AutoScalingGroupName}"
          ImageId: "${aws:ImageId}"
          InstanceId: "${aws:InstanceId}"
          InstanceType: "${aws:InstanceType}"
        metrics_collected:
          disk:
            measurement:
              - used_percent
            metrics_collection_interval: 300
            resources: "{{ ['/'] + (['/hellar/elastic/data'] if inventory_hostname in groups['logs_nodes'] else []) }}"
          mem:
            measurement:
              - mem_used_percent
            metrics_collection_interval: 300
          swap:
            measurement:
              - swap_used_percent
            metrics_collection_interval: 300
