---

# Bootstrap

- name: Remove latency on masternodes before deployment starts
  hosts: masternodes
  become: true
  roles:
    - remove_fake_latency

- name: Set up swap and aws environment vars
  hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Check if inside AWS
      ansible.builtin.uri:
        url: http://169.254.169.254/latest/meta-data
        timeout: 2
      register: aws_uri_check
      failed_when: false
    - name: Set AWS environment variable
      ansible.builtin.set_fact:
        is_aws_environment: '{{ aws_uri_check.status == 200 }}'
  roles:
    - role: aws
      when: is_aws_environment
    - swap

- name: Setup VPN
  hosts: vpn
  become: true
  roles:
    - role: openvpn
      when: openvpn_enabled
      tags: vpn

- name: Setup jq, Python, CWAgent and Docker
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache and install jq
      ansible.builtin.apt:
        pkg:
          - jq
          - unzip
        update_cache: true
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
        version: "6.0.1"
      - name: docker-compose
        version: "1.29.2"
  roles:
    - geerlingguy.pip
    - role: geerlingguy.docker
      vars:
        docker_apt_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
        docker_install_compose: false
        docker_users:
          - ubuntu
    - docker_options
    - eternal_terminal
    - cwagent

- name: Configure tcpdump
  hosts: all
  become: true
  roles:
    - role: tcpdumpd
      when: hellard_network_logging != 0

- name: Setup logs
  hosts: logs_nodes
  become: true
  roles:
    - elastic_stack

- name: Set up miners
  hosts: miners
  become: true
  roles:
    - role: hellar_cli
    - role: hellard
      tags:
        - hellard
    - role: elastic_beats
      core_container_name: hellard

- name: Set up mixers
  hosts: mixer_nodes
  become: true
  roles:
    - role: hellar_cli
    - role: hellard
      tags:
        - hellard
    - role: elastic_beats
      core_container_name: hellard

- name: Set up core and tenderhellar on seed nodes
  hosts: seed_nodes
  become: true
  pre_tasks:
    - name: Set node variables for seed nodes
      ansible.builtin.set_fact:
        node: "{{ seed_nodes[inventory_hostname] }}"
        mode: "seed"
      tags: always
      when: inventory_hostname in seed_nodes
  roles:
    - role: hellar_cli
    - role: hellard
      hellard_listen: true
      hellard_zmq: true
      hellard_indexes: true
      tags:
        - hellard
    - role: tenderhellar
    - role: elastic_beats
      core_container_name: hellard

- name: Set up core on masternodes
  hosts: masternodes
  become: true
  pre_tasks:
    - name: Check inventory for masternodes
      ansible.builtin.set_fact:
        masternode: "{{ masternodes[inventory_hostname] }}"
      tags: always
      when: inventory_hostname in masternodes
    - name: Fail if no masternodes present
      ansible.builtin.fail:
        msg: Masternode not defined in network config
      when: masternode is not defined
  roles:
    - role: hellar_cli
    - role: hellard
      hellard_listen: true
      hellard_zmq: true
      hellard_indexes: true
      tags:
        - hellard
    - mn_status_report
    - role: elastic_beats
      core_container_name: hellard


# Start network

- name: Generate first block to leave IBD mode
  hosts: seed-1
  become: true
  roles:
    - role: generate_firstblock
      when: hellar_network == "devnet" or hellar_network == "regtest"

- name: Start miner
  hosts: miners
  become: true
  roles:
    - role: hellard_generate_miner
      when: hellar_network != "mainnet"

- name: Setup faucet and insight
  hosts: web
  become: true
  roles:
    - multifaucet
    - role: hellar_cli
    - role: hellard
      hellard_indexes: true
      hellard_zmq: true
      hellard_listen: true
    - insight
    - role: elastic_beats
      core_container_name: hellard
  tags:
    - web

- name: Set up wallets
  hosts: wallet_nodes
  become: true
  roles:
    - role: hellar_cli
    - role: hellard
      hellard_indexes: true
      hellard_zmq: true
      enable_wallet: true
      tags:
        - hellard
    - role: elastic_beats
      core_container_name: hellard

# Register masternodes and set sporks

- name: Register masternodes
  hosts: wallet_nodes
  become: true
  roles:
    - role: mn_init
      mnlist: "{{ masternodes }}"
      funding_amount: "{{ masternode_collaterals.mn | int }}"

- name: Update inventory with protx values
  hosts: wallet_nodes
  roles:
    - role: mn_protx_config
      mnlist: "{{ masternodes }}"

- name: Register HP masternodes
  hosts: wallet_nodes
  become: true
  roles:
    - role: mn_init
      mnlist: "{{ hp_masternodes }}"
      funding_amount: "{{ masternode_collaterals.hpmn | int }}"

- name: Update inventory with HPMN protx values
  hosts: wallet_nodes
  roles:
    - role: mn_protx_config
      mnlist: "{{ hp_masternodes }}"

- name: Activate sporks
  hosts: wallet_nodes
  become: true
  roles:
    - role: activate_hellard_sporks
      when: hellar_network != "mainnet" and hellar_network != "testnet"
      delegate_to: '{{ play_hosts | first }}'

# todo: partially working code causes errors in deploy, comment out for now and fix later
# - name: Create governance proposals
#   hosts: wallet_nodes
#   become: true
#   roles:
#     - role: generate_proposals
#       when: governance_proposal_count > 0

- name: Set up core and platform on HP masternodes
  hosts: hp_masternodes
  become: true
  pre_tasks:
    - name: Check inventory for HP masternodes
      ansible.builtin.set_fact:
        node: "{{ hp_masternodes[inventory_hostname] }}"
      tags: always
      when: inventory_hostname in hp_masternodes
  roles:
    - role: hellar_cli
    - role: hellarmate
    - role: mn_status_report
    - role: elastic_beats
      core_container_name: core
      abci_logs_path: "{{ hellarmate_logs_dir }}"

- name: Set up protx diff script
  hosts: masternodes
  become: true
  roles:
    - role: mn_protx_diff

- name: Set up fake latency on masternodes
  hosts: masternodes
  become: true
  roles:
    - role: add_fake_latency
      when: masternode_network_latency
    - role: remove_fake_latency
      when: not masternode_network_latency

- name: Generate hellar.conf for configs repo
  hosts: localhost
  roles:
    - hellar-conf

- name: Clean up
  hosts: all
  become: true
  tasks:
    - name: Prune unused Docker images
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: false
        builder_cache: true
