---

- name: Destroy network
  hosts: all
  become: true
  roles:
    - role: kill_network
      when: target == "network"

- name: Destroy platform
  hosts: hp_masternodes,seed_nodes
  become: true
  roles:
    - role: kill_platform
      when: target == "platform"

- name: Destroy logs
  hosts: logs_nodes
  become: true
  roles:
    - role: kill_logs
      when: target == "logs"
