---

collections:
  - name: ansible.posix
    version: 1.5.1

  - name: ansible.utils
    version: 2.9.0

  - name: community.aws
    version: 6.0.0

  - name: community.crypto
    version: 2.11.1

  - name: community.docker
    version: 3.4.3

  - name: community.general
    version: 6.5.0

roles:
  - src: arillso.logrotate
    version: 1.6.1

  - src: christiangda.amazon_cloudwatch_agent
    version: 2.1.2

  - src: geerlingguy.docker
    version: 6.1.0

  - src: geerlingguy.filebeat
    version: 3.5.0

  - src: geerlingguy.nodejs
    version: 6.1.0

  - src: geerlingguy.pip
    version: 2.2.0

  - src: kyl191.openvpn
    version: v0.9.1
