---

- name: Create multifaucet dirs
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    recurse: true
  with_items:
    - '{{ hellard_home }}/multifaucet/config'

- name: Set up multifaucet services
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ hellard_home }}/multifaucet/{{ item }}'
    mode: "0644"
  with_items:
    - docker-compose.yml
    - init.sql
    - config/faucet.conf.php

- name: Apply multifaucet config
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ hellard_home }}/multifaucet/{{ item }}'
    mode: "0644"
  with_items:
    - config/db.conf.php
    - config/wallet.conf.php

- name: Start multifaucet service
  community.docker.docker_compose:
    project_src: '{{ hellard_home }}/multifaucet'
    state: present
    build: true
    pull: true

- name: Wait for database to be available
  community.docker.docker_container_exec:
    container: multifaucet_db_1
    command: mysqladmin ping -u multifaucet --password="multifaucet"
  register: response
  until: response.stdout == "mysqld is alive"
  retries: 10
  delay: 10

- name: Create promo codes table
  community.docker.docker_container_exec:
    container: multifaucet_db_1
    command: >
      mysql -h localhost -D multifaucet -u multifaucet --password="multifaucet"
      -e 'CREATE TABLE IF NOT EXISTS faucet_promo_codes (id int NOT NULL, code varchar(255), minimum_payout int, maximum_payout int, PRIMARY KEY (id));'

- name: Load MN promo code
  community.docker.docker_container_exec:
    container: multifaucet_db_1
    command: >
      mysql -h localhost -D multifaucet -u multifaucet --password="multifaucet"
      -e 'INSERT IGNORE INTO faucet_promo_codes (id,code,minimum_payout,maximum_payout)
          VALUES (1,"masternode",{{ masternode_collaterals.mn }},{{ masternode_collaterals.mn | int + 10 }});'

- name: Load HPMN promo code
  community.docker.docker_container_exec:
    container: multifaucet_db_1
    command: >
      mysql -h localhost -D multifaucet -u multifaucet --password="multifaucet"
      -e 'INSERT IGNORE INTO faucet_promo_codes (id,code,minimum_payout,maximum_payout)
          VALUES (2,"hp-masternode",{{ masternode_collaterals.hpmn }},{{ masternode_collaterals.hpmn | int + 10 }});'
  when: hellar_network == "devnet"
